FROM docker.io/use-the-fork/snow-blower-devcontainer:latest

# cache /nix
VOLUME /nix

# Allow users to specify a custom config.nix path during build                                       
# ARG SNOW_BLOWER_CONFIG_PATH=.devcontainer/snow-blower-config.nix