FROM docker.io/use-the-fork/snow-blower-devcontainer:latest

# cache /nix
VOLUME /nix

# Allow users to specify a custom config.nix path during build                                       
ARG CONFIG_NIX_PATH=.devcontainer/config.nix