services:
  dev:
    build:
      context: ../
      dockerfile: .devcontainer/Dockerfile
      args:
        USER_UID: ${USER_UID:-1000}
        USER_GID: ${USER_GID:-1000}
    volumes:
      - ..:/workspace:cached
      - ${HOME}/.ssh:/home/code/.ssh:ro

volumes:
  docker:
